sudo: false
language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: MGontavtvWtCcRrb9qKAAlUJVDfwYiG2Yg2LTX9waW2qaDr85joDfkilkdcKAb9syg7SHNY/3AvlkX296Oks6HSlyYvTHPNHvSqYiHqGwnY2nB1DoEO4gIuxEUqtg+qn1O1TSe1v+BKN8Pq56XME8FPGp3uzLMhQJ4e4bzfcKzxkUw8ELQ3pT5eETj3TcbML6l6w77tCqoKzT8vLOhiNBnDcpIDosYrm0ogRemkwwPP+Unpxudb/6gasFIzp+79AZu55FjYI/RhTYQfK8WWxgoS3uo40Ng9gAhgloJlfpWbB44HVGNGYCEGk0t3EHMABKtutEF6XhhK7H1UuQ5qxpII9qCBXMPCpeKSyvCMTjhEqGWJ/Y3ZYsIsrRTH6SrC8YQsOOpDickixJWaX9NFKy3UxYBvUNzw4wQZLDvEgP6QCOeJ6q6N79Mtp1SWcioLYLnBo7A0Z4rCyqgcqYf3uvglpI0qTkaGg2hESQxYAUvHX2ZvRl3c5oTsNqvvuDvWSJu+bD1Dkj2HXm5CpbN/RjE8pipC7UYNYriio6scNknriFndnJphdct7OwBaeA9RWxKM970zq3kZFtcANod+14X38jzZ8BM4ire4Qh03iZxteGQkB88V1Ei1Iqc3XBIKrMEjCoHOsAbiIuNn38EDmIvhQqvvkJqXW7/W6S/KkRiw=
  app: agile-fortress-69453
  on:
    repo: J-Budding/greeter
